INSERT INTO PLAYER (NAME, NATIONALITY, BIRTH_DATE, TITLES) VALUES('Djokovic', 'Serbia', '1987-05-22', 81);
INSERT INTO PLAYER (NAME, NATIONALITY, BIRTH_DATE, TITLES) VALUES('Monfils', 'France', '1986-09-01', 10);
INSERT INTO PLAYER (NAME, NATIONALITY, BIRTH_DATE, TITLES) VALUES('Isner', 'USA', '1985-04-26', 15);